repos:
    -   repo: https://github.com/pre-commit/mirrors-mypy
        rev: v0.761
        hooks:
        -   id: mypy
    -   repo: https://github.com/pre-commit/mirrors-autopep8
        rev: v1.4.4
        hooks:
        -   id: autopep8
    -   repo: https://github.com/pre-commit/mirrors-isort
        rev: v4.3.21
        hooks:
        -   id: isort
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.4.0
        hooks:
        -   id: check-merge-conflict
        -   id: check-json
        -   id: debug-statements
        -   id: detect-aws-credentials
            args: [--allow-missing-credentials]
        -   id: double-quote-string-fixer
        -   id: end-of-file-fixer
        -   id: flake8
        -   id: name-tests-test
        -   id: requirements-txt-fixer
        -   id: trailing-whitespace
    